### ISSUE TITLE
Integration with `gpu4pyscf`

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibochem#71]
I don't know if this has been discussed before, so I'm proposing this integration here. If it has or if there are other plans, please disregard this issue.

There is a PySCF module to integrate with NVIDIA GPUs: https://github.com/pyscf/gpu4pyscf. Maybe it is worth to take a look at it for this repository.

**Comment by chmwzc** [comment]
Thanks for raising this! Personally, I don't think it's going to be useful for us anytime soon, so maybe we'll just keep an eye on it for now? @damarkian any thoughts?

**Comment by yjmaxpayne** [comment]
Thank you, Renato. In general, CPUs are more useful for most quantum chemistry calculations, but GPU acceleration has become increasingly relevant due to the advancements of modern GPUs with large memory. I found the A100 80G results you shared interesting, but I am curious as to why they did not benchmark against the CPU while running PySCF.

**Comment by renatomello** [comment]
> I am curious as to why they did not benchmark against the CPU while running PySCF.

TBH, I don't know why.
